### PR TITLE
Translated Pallete And Category Names To Swedish

### PR DESCRIPTION
**Pull request by Dontknow09**
Don't know when they are visible but it's done

### CODE REVIEW

**Comment by tr7zw** [comment]
grafik
It's the text shown here, so Category buttons, where it's not just the default item name.

**Comment by Dontknow09** [comment]
Oh I see. That makes sense

**Comment by Dontknow09** [comment]
Do you know why the checks fail on my PRs?

**Comment by tr7zw** [comment]
grafik
Just a perms issue for the pipeline since it runs in a context without access to the repo I guess. The main build worked just fine, will merge it later.

**Comment by Dontknow09** [comment]
Ok

**Pull request merged**
