### PR TITLE
Fix translations

### PR DESCRIPTION
**Pull request by RedCommand-dev**
Formatting JSON, fixing a translation not having a JSON format and adding a comma, no changes to actual translation, but just making it actually work lol

### CODE REVIEW

**Comment by RedCommand-dev** [comment]
Note that I formatted based on 4 spaces like found in the mod's java source code

**Comment by tr7zw** [comment]
Hm, these are badly formatted too? Using tabs instead of spaces.

**Comment by tr7zw** [comment]
I use VSCodes (built in?) formatter, that matches the formatting I also use for java code.

**Comment by RedCommand-dev** [comment]
Go to a java file, what do you see in the bottom right? It should tell you how you indent (tabs/spaces: num)

**Comment by tr7zw** [comment]
It's the normal 2 spaces instead of tabs. The lang file was probably copied from another project and not formatted, that's why it had 4 spaces. In the end I don't really care, but tabs are a bit of a nope.

**Comment by RedCommand-dev** [comment]
well I used spaces so is that alr

**Comment by tr7zw** [comment]
grafik
The pr is using tabs.

**Comment by RedCommand-dev** [comment]
My bad, fixed

**Comment by RedCommand-dev** [comment]
Oof, i use 4 spaces

**Comment by RedCommand-dev** [comment]
*now* it should be fixed

**Pull request merged**
