### PR TITLE
Update zh_cn.json

### PR DESCRIPTION
**Pull request by GodGun968**

### CODE REVIEW

**Comment by tr7zw** [comment]
Please also give an ok on https://github.com/tr7zw/ItemSwapper/discussions/116, due to the license change.

**Comment by GodGun968** [comment]
How does this affect me, what should I do

**Comment by AdvancedWipe** [comment]
At the moment the repository is using the GNU GPLv3 license, which is not suitable for Minecraft mods, check out the discussion for a detailed explanation. To change from the current license, everybody has to give the ok to switch to LGPLv3. If your pull request is now merged, we will need your approval as well. Otherwise, your pull request can only be merged after the license change, with your changes being rebased on the license change. This way, you would accept the license as well.

**Comment by tr7zw** [comment]
Yea, basically just need a quick "ok", that you are aware and ok for your language files to be re-licensed under this correct one. (It's just a legal thing, the current license doesn't permit me to change the license of things other people contributed without permission from them)

**Pull request merged**
